; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17

[env:genericSTM32F401CC]
platform = ststm32
board = genericSTM32F401CC
framework = arduino
upload_protocol = stlink
upload_command = openocd -f interface/stlink.cfg -f target/stm32f4x.cfg -c "program {$BUILD_DIR/firmware.elf} verify reset; shutdown"
build_flags = ${env.build_flags} -D USBCON -D USBD_USE_CDC -D STM32_BOARD

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
build_flags = -D ESP32_BOARD   ; Власний макрос для ESP32
